[package]
name = "openvm-example-algebra"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "1c303bfa7fde5d8079b7c1eb13fe310111fdb8fe" }
openvm-platform = { git = "https://github.com/openvm-org/openvm.git", rev = "1c303bfa7fde5d8079b7c1eb13fe310111fdb8fe" }
openvm-algebra-guest = { git = "https://github.com/openvm-org/openvm.git", rev = "1c303bfa7fde5d8079b7c1eb13fe310111fdb8fe" }
openvm-algebra-moduli-setup = { git = "https://github.com/openvm-org/openvm.git", rev = "1c303bfa7fde5d8079b7c1eb13fe310111fdb8fe" }
openvm-algebra-complex-macros = { git = "https://github.com/openvm-org/openvm.git", rev = "1c303bfa7fde5d8079b7c1eb13fe310111fdb8fe" }
serde = { version = "1.0.216", default-features = false, features = [
    "derive",
    "alloc",
] }
num-bigint-dig = { version = "0.8.4", default-features = false }

[features]
default = []
std = ["openvm/std"]
