[package]
name = "openvm-example-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { workspace = true }
openvm-stark-sdk = { workspace = true }

serde = { workspace = true }
hex = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
